name: Build Docker image

on: push

env:
  IMAGE_NAME_LIQUIDE_BLEIBEN: liquide-bleiben
  IMAGE_NAME_CHATBOT: chatbot

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image: [$IMAGE_NAME_LIQUIDE_BLEIBEN, $IMAGE_NAME_CHATBOT]
    steps:
    - uses: actions/checkout@v2

    - name: Build the Docker image $IMAGE_NAME_LIQUIDE_BLEIBEN
      run: docker build . --file Dockerfile --tag $IMAGE_NAME_LIQUIDE_BLEIBEN:$(date +%s)

    - name: Build the Docker image $IMAGE_NAME_CHATBOT
      run: docker build . --file chatbot/Dockerfile --tag $IMAGE_NAME_CHATBOT:$(date +%s)

    - name: List all images
      run: docker images
